config/routes.rb
Rails.application.routes.draw do
  get 'rules/add'
  get 'rules/del'
  get 'games/new', to: 'games#new'
  post 'games/score', to: 'games#score'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
require "open-uri"

class GamesController < ApplicationController
  def initialize
    puts " >>>> INITIALIZE GAMES CONTROLLERS <<<< "
    # executé a chaque action
  end

  def new
    alphabet = ("A".."Z").to_a
    @@biblio = []
    10.times { @@biblio << alphabet.sample }
    @letters = @@biblio
  end

  def score
    session[:score] = 0 if session[:score].nil?
    @word = params["word"].upcase
    if  !@word.split("").all?{ |letter| @@biblio.include?(letter) }
      @answer = "Sorry, but #{@word.upcase} can't be built out of #{@@biblio.join(', ')}"
    else
      url = "https://wagon-dictionary.herokuapp.com/#{@word}";
      response = JSON.parse(open(url).read)
      if(response["found"] == true)
        @answer = "Congratulation"
        session[:score] += @word.length;
      else
        @answer = "Sorry but #{@word.upcase} does not seem to be a valid English word..."
      end
    end
    @score = session[:score]
  end
end

app/controllers/rules_controller.rb
class RulesController < ApplicationController
  def add
  end

  def del
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/rules_helper.rb
module RulesHelper
end

app/views/games/new.html.erb
<h1>New Game</h1>
<ul>
  <%  @letters.each{ |letter| %>
    <li><%= letter %></li>
  <% } %>
</ul>
<p>What is the longest word you can find ?  </p>
<form action="/games/score" method="post">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <div id="play-put">
    <input type="text" name="word" id="word">
    <input type="submit" value="Play" id="play">
  </div>
</form>

app/views/games/score.html.erb
<h1>Result</h1>
<p>Score: <%= @score %></p>
<p><%= @answer %></p>
<%= link_to "Play again", games_new_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLongestWordGame</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rules/add.html.erb
<h1>Rules#add</h1>
<p>Find me in app/views/rules/add.html.erb</p>

app/views/rules/del.html.erb
<h1>Rules#del</h1>
<p>Find me in app/views/rules/del.html.erb</p>